### ISSUE TITLE
Support for transparent barcodes without background ?

### ISSUE THREAD

**Issue by yaolet** [adrienv1520/bitgener#17]

**Comment by adrienv1520** [comment]
Great idea, I'll do it soon and let you know. ;)

**Comment by yaolet** [comment]
I've made a slight twist on it. 

```
  let bgrect = settings.bgColor === null?  "":
    `<rect width="${width}" 
         height="${height}" 
         x="0" y="0"
         fill="${settings.bgColor}" 
         opacity="${settings.opacity}" />
```
with an additional opacity control.

**Comment by adrienv1520** [comment]
Thanks mate, you saved me some time.

I've just made a new release, related PR is #20 

Version [1.2.0](https://github.com/adrienv1520/bitgener/releases/tag/1.2.0) now has opacity options for the bars/hri and the background!

Check it out ;)

I'll update the demo too soon. Thanks again and let me know what you think about it.

**Comment by adrienv1520** [comment]
Demo updated: https://bitgener.herokuapp.com/

Have a look ;)
