### ISSUE TITLE
Computing weights for EAN13 code

### ISSUE THREAD

**Issue by ElMatella** [adrienv1520/bitgener#35]
Hey!

I came across your package and it seems really good! Thank you for the work.

I have a little problem with ean13 codes and final key generation. Correct me if I am wrong but you are using this code to generate the ean final key:

```javascript
  // check each digit is numeric and construct the data to compute
  let sum = 0;
  let odd = false;

  for (let i = 0; i < dataLength; i += 1) {
    const intChar = int(data.charAt(i));

    if (intChar === undefined) {
      const error = new LibError(LibError.Codes.INVALID_DATA);
      error.setMessage(`data to encode must contain only numerical digits, got '${data}'`);

      throw error;
    }

    sum += (odd ? 1 : 3) * intChar;
    odd = !odd;
  }

  const dataToEncode = `${data}${(10 - (sum % 10)) % 10}`;
```

[According to wikipedia](https://fr.wikipedia.org/wiki/EAN_13) (screenshot at the end of this issue), weights for ean 13 begins at 1, when ean 8 begins at 3. This makes the final key for ean13 products wrong. 

This could be easily fixed by changing `let odd = false;` to` let odd = type !== 'ean8'`. 

Am I missing something here? If not, do you want me to make a pull request? 

![Capture d’écran 2020-09-18 à 09 13 19](https://user-images.githubusercontent.com/7662722/93567670-4b77bf80-f98f-11ea-8c25-9bac03474522.png)

**Comment by adrienv1520** [comment]
Hi @ElMatella thanks a lot for your feedback and opening this issue!

I looked at the code and there is a big mistake to be fixed, you're right. Saw your PR too. I need to look at the code to be sure there is no other collacteral issues, check other encodings too ti be sure there are no other mistakes.

By the way, I will add missing github pages for contributing and other stuff, that was missing, I need to improve this part.

I'll do all of this stuff this week and come back to you asap. I'm currently updating the debugger too on develop so I'll do my best to come up with a stable version quickly.

Thanks again.

**Comment by adrienv1520** [comment]
Hi @ElMatella !

Sorry to come back to you so late, I had a lot of work to do on node-uri.

So I couldn't have merged your PR as actually the whole algorithm was wrong.

Ean codes should have been built from right to left and not the opposite which made **ean13** encoding wrong in the first place. Changing the boolean *odd* made **ean13** working fine but **ean8** was having errors. Changing the algorithm resolved the issue.

Thank you for reporting this issue, never noticed this then.

**Comment by ElMatella** [comment]
Thank you for following up with this! Have a nice day and feel free to close this issue :100:
