### ISSUE TITLE
Node version in "engines" is too specific

### ISSUE THREAD

**Issue by Manny651** [adrienv1520/bitgener#9]
The engines section in the package.json indicates that this library only works with Node v10.16.2, which generates warnings or errors during install depending on the npm or Yarn "engine strict" settings. As far as I can see, this library doesn't depend on anything specific to Node v10.16.

**Comment by adrienv1520** [comment]
Hi,

Thanks for the feedback and sorry for the delay. You're totally right, my bad. I have fixed it here: #10 

Version 1.1.2 embeds this fix: https://github.com/adrienv1520/bitgener/releases/tag/1.1.2
